

class StoryBlokConstants:
    STORYBLOK_COVER_THUMBNAIL_HOST = 'https://storyblok-image.ef.com.cn/unsafe'
    STORYBLOK_COVER_THUMBNAIL_WIDTH_221 = '221'
    STORYBLOK_COVER_THUMBNAIL_WIDTH_442 = '442'
    STORYBLOK_COVER_THUMBNAIL_WIDTH_663 = '663'
    STORYBLOK_COVER_THUMBNAIL_HEIGHT = '0'
    STORYBLOK_COVER_THUMBNAIL_RESOLUTION_1 = '{0}x{1}'.format(STORYBLOK_COVER_THUMBNAIL_WIDTH_221,
                                                              STORYBLOK_COVER_THUMBNAIL_HEIGHT)
    STORYBLOK_COVER_THUMBNAIL_RESOLUTION_2 = '{0}x{1}'.format(STORYBLOK_COVER_THUMBNAIL_WIDTH_442,
                                                              STORYBLOK_COVER_THUMBNAIL_HEIGHT)
    STORYBLOK_COVER_THUMBNAIL_RESOLUTION_3 = '{0}x{1}'.format(STORYBLOK_COVER_THUMBNAIL_WIDTH_663,
                                                              STORYBLOK_COVER_THUMBNAIL_HEIGHT)
