version: '3.7'

services:
  kidsqa_python3:
    image: edtech-kt/kt-qa-api-test:${IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./Dockerfile
      network: host
  maven:
    image: edtech-kt/Maven:${IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./DockerfileM