class PipelinePublishConstants:
    FIELD_ID = 'id'
    FIELD_TITLE = 'title'
    FIELD_PATH = 'path'
    FIELD_ORIGINID = 'originID'
    FIELD_LESSONS = 'lessons'
    FIELD_CHILDREN = 'children'
    FIELD_REGION_LESSONS = 'regionLessons'
    FIELD_CONTENT_ID = 'contentId'
    FIELD_CONTENT_REVISION = 'contentRevision'
    FIELD_SCHEMA_REVISION = 'schemaVersion'
    FIELD_CHILDREFS = 'childRefs'
    FIELD_URL = 'url'
    FIELD_DATA = 'data'
    FIELD_MIME_TYPE = 'mimeType'
